name: pygeode
channels:
  - conda-forge
  - default
dependencies:
  - python=3.10
  - numpy
  - scipy
  - gsl
  - cartopy
  - netcdf4
  - pip
  - pip:
    - matplotlib
    - xarray
    - dask
    - progressbar2
